import type { Deal } from "@/lib/types";

const steamAppIds: Record<string, number> = {
  "The Witcher 3": 292030,
  "Red Dead Redemption 2": 1174180,
  "Celeste": 504230,
  "Dead Space": 1693980,
  "Dead Cells": 588650,
  "Cyberpunk 2077": 1091500,
  "Disco Elysium": 632470,
  "God of War": 1593500,
  "Ori Will of Wisps": 1057090,
  "Hollow Knight": 367520,
  "Hades": 1145360,
  "Slay the Spire": 646570,
  "Inscryption": 1092790,
  "Cuphead": 268910,
  "Stardew Valley": 413150,
  "Elden Ring": 1245620,
  "Baldur's Gate 3": 1086940,
  "Black Myth Wukong": 2358720,
  "Balatro": 2379780,
  "Helldivers 2": 553850,
  "Indiana Jones": 2677660,
  "Resident Evil 4": 2050650,
  "Jedi Survivor": 1774580,
  "Hogwarts Legacy": 990080,
  "Sifu": 2138710,
};

function cover(name: string): string {
  const appId = steamAppIds[name];
  if (appId) {
    return `https://cdn.akamai.steamstatic.com/steam/apps/${appId}/header.jpg`;
  }
  return `https://placehold.co/460x215/1A1A2E/F5A623?text=${encodeURIComponent(name)}`;
}

export const mockDeals: Deal[] = [
  // ─── Flash Sales ───────────────────────────────────────────
  {
    id: "d1",
    gameId: "g6",
    storeId: "s2",
    title: "The Witcher 3: Wild Hunt",
    coverImage: cover("The Witcher 3"),
    currentPrice: 9.99,
    originalPrice: 39.99,
    discount: 75,
    dealScore: 97,
    scoreBreakdown: {
      historicalLowFactor: 95,
      predictionFactor: 98,
      storeTrustFactor: 96,
      priceTrendFactor: 92,
      regionCompatibility: 100,
      editionValue: 95,
      timeSensitivity: 90,
    },
    recommendation: "strong-buy",
    tags: ["Flash Sale", "Historical Low"],
    expiresAt: "2025-02-15T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d2",
    gameId: "g5",
    storeId: "s1",
    title: "Red Dead Redemption 2",
    coverImage: cover("Red Dead Redemption 2"),
    currentPrice: 19.99,
    originalPrice: 59.99,
    discount: 67,
    dealScore: 95,
    scoreBreakdown: {
      historicalLowFactor: 92,
      predictionFactor: 96,
      storeTrustFactor: 98,
      priceTrendFactor: 94,
      regionCompatibility: 100,
      editionValue: 88,
      timeSensitivity: 85,
    },
    recommendation: "strong-buy",
    tags: ["Flash Sale", "Trending"],
    expiresAt: "2025-02-10T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d3",
    gameId: "g27",
    storeId: "s1",
    title: "Celeste",
    coverImage: cover("Celeste"),
    currentPrice: 4.99,
    originalPrice: 19.99,
    discount: 75,
    dealScore: 96,
    scoreBreakdown: {
      historicalLowFactor: 98,
      predictionFactor: 95,
      storeTrustFactor: 98,
      priceTrendFactor: 90,
      regionCompatibility: 100,
      editionValue: 92,
      timeSensitivity: 88,
    },
    recommendation: "strong-buy",
    tags: ["Flash Sale", "Historical Low"],
    expiresAt: "2025-02-12T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d4",
    gameId: "g17",
    storeId: "s5",
    title: "Dead Space Remake",
    coverImage: cover("Dead Space"),
    currentPrice: 23.99,
    originalPrice: 59.99,
    discount: 60,
    dealScore: 90,
    scoreBreakdown: {
      historicalLowFactor: 88,
      predictionFactor: 92,
      storeTrustFactor: 91,
      priceTrendFactor: 90,
      regionCompatibility: 95,
      editionValue: 85,
      timeSensitivity: 82,
    },
    recommendation: "strong-buy",
    tags: ["Flash Sale"],
    expiresAt: "2025-02-14T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d5",
    gameId: "g37",
    storeId: "s1",
    title: "Dead Cells",
    coverImage: cover("Dead Cells"),
    currentPrice: 7.49,
    originalPrice: 24.99,
    discount: 70,
    dealScore: 93,
    scoreBreakdown: {
      historicalLowFactor: 94,
      predictionFactor: 91,
      storeTrustFactor: 98,
      priceTrendFactor: 88,
      regionCompatibility: 100,
      editionValue: 90,
      timeSensitivity: 80,
    },
    recommendation: "strong-buy",
    tags: ["Flash Sale", "Editor's Pick"],
    expiresAt: "2025-02-11T23:59:59Z",
    url: "#",
    platform: "pc",
  },

  // ─── Historical Lows ──────────────────────────────────────
  {
    id: "d6",
    gameId: "g2",
    storeId: "s2",
    title: "Cyberpunk 2077",
    coverImage: cover("Cyberpunk 2077"),
    currentPrice: 29.99,
    originalPrice: 59.99,
    discount: 50,
    dealScore: 91,
    scoreBreakdown: {
      historicalLowFactor: 96,
      predictionFactor: 90,
      storeTrustFactor: 96,
      priceTrendFactor: 88,
      regionCompatibility: 100,
      editionValue: 82,
      timeSensitivity: 75,
    },
    recommendation: "strong-buy",
    tags: ["Historical Low", "Editor's Pick"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d7",
    gameId: "g32",
    storeId: "s2",
    title: "Disco Elysium - The Final Cut",
    coverImage: cover("Disco Elysium"),
    currentPrice: 9.99,
    originalPrice: 39.99,
    discount: 75,
    dealScore: 96,
    scoreBreakdown: {
      historicalLowFactor: 99,
      predictionFactor: 94,
      storeTrustFactor: 96,
      priceTrendFactor: 92,
      regionCompatibility: 100,
      editionValue: 95,
      timeSensitivity: 70,
    },
    recommendation: "strong-buy",
    tags: ["Historical Low"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d8",
    gameId: "g7",
    storeId: "s1",
    title: "God of War",
    coverImage: cover("God of War"),
    currentPrice: 19.99,
    originalPrice: 49.99,
    discount: 60,
    dealScore: 92,
    scoreBreakdown: {
      historicalLowFactor: 94,
      predictionFactor: 90,
      storeTrustFactor: 98,
      priceTrendFactor: 90,
      regionCompatibility: 100,
      editionValue: 88,
      timeSensitivity: 78,
    },
    recommendation: "strong-buy",
    tags: ["Historical Low", "Trending"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d9",
    gameId: "g35",
    storeId: "s1",
    title: "Ori and the Will of the Wisps",
    coverImage: cover("Ori Will of Wisps"),
    currentPrice: 7.49,
    originalPrice: 29.99,
    discount: 75,
    dealScore: 95,
    scoreBreakdown: {
      historicalLowFactor: 97,
      predictionFactor: 93,
      storeTrustFactor: 98,
      priceTrendFactor: 91,
      regionCompatibility: 100,
      editionValue: 92,
      timeSensitivity: 72,
    },
    recommendation: "strong-buy",
    tags: ["Historical Low"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d10",
    gameId: "g28",
    storeId: "s1",
    title: "Hollow Knight",
    coverImage: cover("Hollow Knight"),
    currentPrice: 7.49,
    originalPrice: 14.99,
    discount: 50,
    dealScore: 95,
    scoreBreakdown: {
      historicalLowFactor: 96,
      predictionFactor: 94,
      storeTrustFactor: 98,
      priceTrendFactor: 92,
      regionCompatibility: 100,
      editionValue: 97,
      timeSensitivity: 65,
    },
    recommendation: "strong-buy",
    tags: ["Historical Low", "Editor's Pick"],
    url: "#",
    platform: "pc",
  },

  // ─── Bundle Deals ─────────────────────────────────────────
  {
    id: "d11",
    gameId: "g26",
    storeId: "s4",
    title: "Hades",
    coverImage: cover("Hades"),
    currentPrice: 10.49,
    originalPrice: 24.99,
    discount: 58,
    dealScore: 93,
    scoreBreakdown: {
      historicalLowFactor: 90,
      predictionFactor: 88,
      storeTrustFactor: 93,
      priceTrendFactor: 86,
      regionCompatibility: 100,
      editionValue: 94,
      timeSensitivity: 92,
    },
    recommendation: "strong-buy",
    tags: ["Bundle Deal", "Editor's Pick"],
    expiresAt: "2025-03-01T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d12",
    gameId: "g36",
    storeId: "s4",
    title: "Slay the Spire",
    coverImage: cover("Slay the Spire"),
    currentPrice: 8.49,
    originalPrice: 24.99,
    discount: 66,
    dealScore: 92,
    scoreBreakdown: {
      historicalLowFactor: 91,
      predictionFactor: 89,
      storeTrustFactor: 93,
      priceTrendFactor: 88,
      regionCompatibility: 100,
      editionValue: 90,
      timeSensitivity: 88,
    },
    recommendation: "strong-buy",
    tags: ["Bundle Deal"],
    expiresAt: "2025-03-01T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d13",
    gameId: "g45",
    storeId: "s4",
    title: "Inscryption",
    coverImage: cover("Inscryption"),
    currentPrice: 6.99,
    originalPrice: 19.99,
    discount: 65,
    dealScore: 92,
    scoreBreakdown: {
      historicalLowFactor: 93,
      predictionFactor: 90,
      storeTrustFactor: 93,
      priceTrendFactor: 87,
      regionCompatibility: 100,
      editionValue: 92,
      timeSensitivity: 85,
    },
    recommendation: "strong-buy",
    tags: ["Bundle Deal", "Editor's Pick"],
    expiresAt: "2025-03-01T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d14",
    gameId: "g34",
    storeId: "s4",
    title: "Cuphead",
    coverImage: cover("Cuphead"),
    currentPrice: 9.99,
    originalPrice: 19.99,
    discount: 50,
    dealScore: 90,
    scoreBreakdown: {
      historicalLowFactor: 88,
      predictionFactor: 86,
      storeTrustFactor: 93,
      priceTrendFactor: 85,
      regionCompatibility: 100,
      editionValue: 88,
      timeSensitivity: 90,
    },
    recommendation: "buy",
    tags: ["Bundle Deal"],
    expiresAt: "2025-03-01T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d15",
    gameId: "g29",
    storeId: "s4",
    title: "Stardew Valley",
    coverImage: cover("Stardew Valley"),
    currentPrice: 10.49,
    originalPrice: 14.99,
    discount: 30,
    dealScore: 88,
    scoreBreakdown: {
      historicalLowFactor: 85,
      predictionFactor: 82,
      storeTrustFactor: 93,
      priceTrendFactor: 80,
      regionCompatibility: 100,
      editionValue: 94,
      timeSensitivity: 88,
    },
    recommendation: "buy",
    tags: ["Bundle Deal", "Trending"],
    expiresAt: "2025-03-01T23:59:59Z",
    url: "#",
    platform: "pc",
  },

  // ─── Trending ─────────────────────────────────────────────
  {
    id: "d16",
    gameId: "g1",
    storeId: "s5",
    title: "Elden Ring",
    coverImage: cover("Elden Ring"),
    currentPrice: 35.99,
    originalPrice: 59.99,
    discount: 40,
    dealScore: 82,
    scoreBreakdown: {
      historicalLowFactor: 78,
      predictionFactor: 80,
      storeTrustFactor: 91,
      priceTrendFactor: 82,
      regionCompatibility: 95,
      editionValue: 78,
      timeSensitivity: 72,
    },
    recommendation: "buy",
    tags: ["Trending"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d17",
    gameId: "g3",
    storeId: "s1",
    title: "Baldur's Gate 3",
    coverImage: cover("Baldur's Gate 3"),
    currentPrice: 53.99,
    originalPrice: 59.99,
    discount: 10,
    dealScore: 68,
    scoreBreakdown: {
      historicalLowFactor: 55,
      predictionFactor: 72,
      storeTrustFactor: 98,
      priceTrendFactor: 60,
      regionCompatibility: 100,
      editionValue: 70,
      timeSensitivity: 50,
    },
    recommendation: "wait",
    tags: ["Trending"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d18",
    gameId: "g23",
    storeId: "s1",
    title: "Black Myth: Wukong",
    coverImage: cover("Black Myth Wukong"),
    currentPrice: 47.99,
    originalPrice: 59.99,
    discount: 20,
    dealScore: 71,
    scoreBreakdown: {
      historicalLowFactor: 65,
      predictionFactor: 75,
      storeTrustFactor: 98,
      priceTrendFactor: 68,
      regionCompatibility: 100,
      editionValue: 60,
      timeSensitivity: 55,
    },
    recommendation: "wait",
    tags: ["Trending", "New Release"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d19",
    gameId: "g43",
    storeId: "s1",
    title: "Balatro",
    coverImage: cover("Balatro"),
    currentPrice: 11.24,
    originalPrice: 14.99,
    discount: 25,
    dealScore: 80,
    scoreBreakdown: {
      historicalLowFactor: 76,
      predictionFactor: 78,
      storeTrustFactor: 98,
      priceTrendFactor: 74,
      regionCompatibility: 100,
      editionValue: 82,
      timeSensitivity: 68,
    },
    recommendation: "buy",
    tags: ["Trending", "Editor's Pick"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d20",
    gameId: "g21",
    storeId: "s1",
    title: "Helldivers 2",
    coverImage: cover("Helldivers 2"),
    currentPrice: 31.99,
    originalPrice: 39.99,
    discount: 20,
    dealScore: 76,
    scoreBreakdown: {
      historicalLowFactor: 70,
      predictionFactor: 78,
      storeTrustFactor: 98,
      priceTrendFactor: 72,
      regionCompatibility: 100,
      editionValue: 68,
      timeSensitivity: 60,
    },
    recommendation: "buy",
    tags: ["Trending"],
    url: "#",
    platform: "pc",
  },

  // ─── New Releases / Limited Time ──────────────────────────
  {
    id: "d21",
    gameId: "g25",
    storeId: "s3",
    title: "Indiana Jones and the Great Circle",
    coverImage: cover("Indiana Jones"),
    currentPrice: 55.99,
    originalPrice: 69.99,
    discount: 20,
    dealScore: 66,
    scoreBreakdown: {
      historicalLowFactor: 62,
      predictionFactor: 68,
      storeTrustFactor: 94,
      priceTrendFactor: 58,
      regionCompatibility: 100,
      editionValue: 60,
      timeSensitivity: 48,
    },
    recommendation: "wait",
    tags: ["New Release", "Limited Time"],
    expiresAt: "2025-02-20T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d22",
    gameId: "g11",
    storeId: "s6",
    title: "Resident Evil 4",
    coverImage: cover("Resident Evil 4"),
    currentPrice: 27.99,
    originalPrice: 59.99,
    discount: 53,
    dealScore: 89,
    scoreBreakdown: {
      historicalLowFactor: 90,
      predictionFactor: 88,
      storeTrustFactor: 89,
      priceTrendFactor: 86,
      regionCompatibility: 95,
      editionValue: 85,
      timeSensitivity: 80,
    },
    recommendation: "strong-buy",
    tags: ["Limited Time", "Trending"],
    expiresAt: "2025-02-18T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d23",
    gameId: "g18",
    storeId: "s3",
    title: "Star Wars Jedi: Survivor",
    coverImage: cover("Jedi Survivor"),
    currentPrice: 27.99,
    originalPrice: 69.99,
    discount: 60,
    dealScore: 87,
    scoreBreakdown: {
      historicalLowFactor: 86,
      predictionFactor: 84,
      storeTrustFactor: 94,
      priceTrendFactor: 88,
      regionCompatibility: 100,
      editionValue: 80,
      timeSensitivity: 76,
    },
    recommendation: "buy",
    tags: ["Limited Time"],
    expiresAt: "2025-02-16T23:59:59Z",
    url: "#",
    platform: "pc",
  },
  {
    id: "d24",
    gameId: "g8",
    storeId: "s5",
    title: "Hogwarts Legacy",
    coverImage: cover("Hogwarts Legacy"),
    currentPrice: 29.99,
    originalPrice: 59.99,
    discount: 50,
    dealScore: 85,
    scoreBreakdown: {
      historicalLowFactor: 84,
      predictionFactor: 82,
      storeTrustFactor: 91,
      priceTrendFactor: 84,
      regionCompatibility: 95,
      editionValue: 80,
      timeSensitivity: 78,
    },
    recommendation: "buy",
    tags: ["Trending", "Editor's Pick"],
    url: "#",
    platform: "pc",
  },
  {
    id: "d25",
    gameId: "g49",
    storeId: "s3",
    title: "Sifu",
    coverImage: cover("Sifu"),
    currentPrice: 13.99,
    originalPrice: 39.99,
    discount: 65,
    dealScore: 88,
    scoreBreakdown: {
      historicalLowFactor: 87,
      predictionFactor: 85,
      storeTrustFactor: 94,
      priceTrendFactor: 86,
      regionCompatibility: 100,
      editionValue: 82,
      timeSensitivity: 75,
    },
    recommendation: "buy",
    tags: ["Limited Time", "Historical Low"],
    expiresAt: "2025-02-22T23:59:59Z",
    url: "#",
    platform: "pc",
  },
];
