import type { Game } from "@/lib/types";

function cover(name: string): string {
  return `https://placehold.co/460x215/1A1A2E/F5A623?text=${encodeURIComponent(name)}`;
}

export const mockGames: Game[] = [
  // ─── AAA TITLES ──────────────────────────────────────────────
  {
    id: "g1",
    slug: "elden-ring",
    title: "Elden Ring",
    coverImage: cover("Elden Ring"),
    description:
      "An epic action RPG set in the Lands Between, created by Hidetaka Miyazaki and George R.R. Martin. Explore a vast open world full of danger and discovery.",
    shortDescription: "Open-world action RPG from FromSoftware and George R.R. Martin.",
    metadata: {
      developer: "FromSoftware",
      publisher: "Bandai Namco Entertainment",
      releaseDate: "2022-02-25",
      genres: ["action", "rpg", "open-world", "souls-like"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Co-op", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g1-std", gameId: "g1", name: "Elden Ring", edition: "standard", includes: ["Base Game"] },
      { id: "g1-dlx", gameId: "g1", name: "Elden Ring Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Digital Artbook", "Digital Soundtrack"] },
    ],
    bestPrice: 35.99,
    bestPriceStoreId: "s5",
    originalPrice: 59.99,
    discount: 40,
    dealScore: 82,
    isOnSale: true,
  },
  {
    id: "g2",
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    coverImage: cover("Cyberpunk 2077"),
    description:
      "An open-world action RPG set in Night City, a megalopolis obsessed with power, glamour, and body modification. Play as V, a mercenary outlaw going after a one-of-a-kind implant.",
    shortDescription: "Open-world action RPG set in the dystopian Night City.",
    metadata: {
      developer: "CD Projekt Red",
      publisher: "CD Projekt",
      releaseDate: "2020-12-10",
      genres: ["action", "rpg", "open-world"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Japanese", "Polish", "Chinese"],
    },
    editions: [
      { id: "g2-std", gameId: "g2", name: "Cyberpunk 2077", edition: "standard", includes: ["Base Game"] },
      { id: "g2-ult", gameId: "g2", name: "Cyberpunk 2077 Ultimate Edition", edition: "ultimate", includes: ["Base Game", "Phantom Liberty DLC"] },
    ],
    bestPrice: 29.99,
    bestPriceStoreId: "s2",
    originalPrice: 59.99,
    discount: 50,
    dealScore: 91,
    isOnSale: true,
  },
  {
    id: "g3",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    coverImage: cover("Baldur's Gate 3"),
    description:
      "A sprawling RPG based on D&D 5th Edition, featuring turn-based combat, deep character creation, and a rich narrative with meaningful choices across over 100 hours of content.",
    shortDescription: "Epic D&D RPG with turn-based combat and deep narrative choices.",
    metadata: {
      developer: "Larian Studios",
      publisher: "Larian Studios",
      releaseDate: "2023-08-03",
      genres: ["rpg", "strategy", "adventure"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Portuguese", "Chinese", "Korean"],
    },
    editions: [
      { id: "g3-std", gameId: "g3", name: "Baldur's Gate 3", edition: "standard", includes: ["Base Game"] },
      { id: "g3-dlx", gameId: "g3", name: "Baldur's Gate 3 Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Digital Artbook", "Digital Soundtrack", "Dice Skin"] },
    ],
    bestPrice: 53.99,
    bestPriceStoreId: "s1",
    originalPrice: 59.99,
    discount: 10,
    dealScore: 68,
    isOnSale: true,
  },
  {
    id: "g4",
    slug: "starfield",
    title: "Starfield",
    coverImage: cover("Starfield"),
    description:
      "Bethesda's first new universe in 25 years. Explore over 1,000 planets in the settled systems, join factions, and unravel the greatest mystery of all time.",
    shortDescription: "Bethesda's epic space exploration RPG across 1,000 planets.",
    metadata: {
      developer: "Bethesda Game Studios",
      publisher: "Bethesda Softworks",
      releaseDate: "2023-09-06",
      genres: ["rpg", "action", "open-world"],
      platforms: ["pc", "xbox"],
      features: ["Single Player", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Japanese", "Chinese"],
    },
    editions: [
      { id: "g4-std", gameId: "g4", name: "Starfield", edition: "standard", includes: ["Base Game"] },
      { id: "g4-prm", gameId: "g4", name: "Starfield Premium Edition", edition: "deluxe", includes: ["Base Game", "Shattered Space DLC", "Skin Pack"] },
    ],
    bestPrice: 34.99,
    bestPriceStoreId: "s3",
    originalPrice: 69.99,
    discount: 50,
    dealScore: 78,
    isOnSale: true,
  },
  {
    id: "g5",
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    coverImage: cover("Red Dead Redemption 2"),
    description:
      "An epic tale of life in America's unforgiving heartland. Arthur Morgan must deal with the decline of the Wild West whilst trying to survive against government forces and rival gangs.",
    shortDescription: "Epic open-world Western adventure from Rockstar Games.",
    metadata: {
      developer: "Rockstar Games",
      publisher: "Rockstar Games",
      releaseDate: "2019-11-05",
      genres: ["action", "adventure", "open-world"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Chinese", "Japanese", "Korean"],
    },
    editions: [
      { id: "g5-std", gameId: "g5", name: "Red Dead Redemption 2", edition: "standard", includes: ["Base Game"] },
      { id: "g5-ult", gameId: "g5", name: "Red Dead Redemption 2 Ultimate Edition", edition: "ultimate", includes: ["Base Game", "Bonus Story Content", "Online Bonuses"] },
    ],
    bestPrice: 19.99,
    bestPriceStoreId: "s1",
    originalPrice: 59.99,
    discount: 67,
    dealScore: 95,
    isOnSale: true,
  },
  {
    id: "g6",
    slug: "the-witcher-3-wild-hunt",
    title: "The Witcher 3: Wild Hunt",
    coverImage: cover("The Witcher 3"),
    description:
      "A story-driven open-world RPG set in a visually stunning fantasy universe. As Geralt of Rivia, track down the Child of Prophecy in a vast world rich with merchant cities and dangerous wilds.",
    shortDescription: "Award-winning open-world RPG following monster hunter Geralt.",
    metadata: {
      developer: "CD Projekt Red",
      publisher: "CD Projekt",
      releaseDate: "2015-05-19",
      genres: ["rpg", "action", "open-world"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Polish", "Japanese", "Chinese", "Korean"],
    },
    editions: [
      { id: "g6-std", gameId: "g6", name: "The Witcher 3: Wild Hunt", edition: "standard", includes: ["Base Game"] },
      { id: "g6-cmp", gameId: "g6", name: "The Witcher 3: Wild Hunt - Complete Edition", edition: "complete", includes: ["Base Game", "Hearts of Stone", "Blood and Wine", "16 Free DLC"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s2",
    originalPrice: 39.99,
    discount: 75,
    dealScore: 97,
    isOnSale: true,
  },
  {
    id: "g7",
    slug: "god-of-war",
    title: "God of War",
    coverImage: cover("God of War"),
    description:
      "Kratos returns in a deeply personal quest through the realms of Norse mythology. Together with his son Atreus, he must face gods and monsters across a dangerous and beautiful world.",
    shortDescription: "Kratos and Atreus journey through Norse mythology.",
    metadata: {
      developer: "Santa Monica Studio",
      publisher: "PlayStation PC LLC",
      releaseDate: "2022-01-14",
      genres: ["action", "adventure"],
      platforms: ["pc", "playstation"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g7-std", gameId: "g7", name: "God of War", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 19.99,
    bestPriceStoreId: "s1",
    originalPrice: 49.99,
    discount: 60,
    dealScore: 92,
    isOnSale: true,
  },
  {
    id: "g8",
    slug: "hogwarts-legacy",
    title: "Hogwarts Legacy",
    coverImage: cover("Hogwarts Legacy"),
    description:
      "Experience life as a student at Hogwarts in the 1800s. Master spells, brew potions, tame magical beasts, and explore the open world in this immersive action RPG.",
    shortDescription: "Open-world action RPG set in the Harry Potter universe.",
    metadata: {
      developer: "Avalanche Software",
      publisher: "Warner Bros. Games",
      releaseDate: "2023-02-10",
      genres: ["rpg", "action", "open-world", "adventure"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g8-std", gameId: "g8", name: "Hogwarts Legacy", edition: "standard", includes: ["Base Game"] },
      { id: "g8-dlx", gameId: "g8", name: "Hogwarts Legacy Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Dark Arts Pack", "Dark Arts Battle Arena", "Thestral Mount"] },
    ],
    bestPrice: 29.99,
    bestPriceStoreId: "s5",
    originalPrice: 59.99,
    discount: 50,
    dealScore: 85,
    isOnSale: true,
  },
  {
    id: "g9",
    slug: "grand-theft-auto-v",
    title: "GTA V",
    coverImage: cover("GTA V"),
    description:
      "Experience the sprawling world of Los Santos and Blaine County in the definitive open-world game. Switch between three protagonists and explore a world of crime, heists, and chaos.",
    shortDescription: "Iconic open-world crime epic set in Los Santos.",
    metadata: {
      developer: "Rockstar North",
      publisher: "Rockstar Games",
      releaseDate: "2015-04-14",
      genres: ["action", "adventure", "open-world"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Russian", "Chinese", "Japanese", "Korean"],
    },
    editions: [
      { id: "g9-std", gameId: "g9", name: "Grand Theft Auto V", edition: "standard", includes: ["Base Game", "GTA Online"] },
    ],
    bestPrice: 14.99,
    bestPriceStoreId: "s12",
    originalPrice: 29.99,
    discount: 50,
    dealScore: 88,
    isOnSale: true,
  },
  {
    id: "g10",
    slug: "marvels-spider-man-remastered",
    title: "Spider-Man Remastered",
    coverImage: cover("Spider-Man Remastered"),
    description:
      "Swing through Marvel's New York as Spider-Man in this action-adventure masterpiece. Features the complete original game plus The City That Never Sleeps DLC.",
    shortDescription: "Swing through New York as the iconic web-slinger.",
    metadata: {
      developer: "Insomniac Games",
      publisher: "PlayStation PC LLC",
      releaseDate: "2022-08-12",
      genres: ["action", "adventure", "open-world"],
      platforms: ["pc", "playstation"],
      features: ["Single Player", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Chinese"],
    },
    editions: [
      { id: "g10-std", gameId: "g10", name: "Marvel's Spider-Man Remastered", edition: "standard", includes: ["Base Game", "The City That Never Sleeps DLC"] },
    ],
    bestPrice: 29.99,
    bestPriceStoreId: "s1",
    originalPrice: 59.99,
    discount: 50,
    dealScore: 86,
    isOnSale: true,
  },
  {
    id: "g11",
    slug: "resident-evil-4-remake",
    title: "Resident Evil 4",
    coverImage: cover("Resident Evil 4"),
    description:
      "A reimagining of the survival horror classic. Six years after Raccoon City, Leon S. Kennedy is sent to rescue the president's kidnapped daughter from a sinister rural European village.",
    shortDescription: "Masterful remake of the survival horror classic.",
    metadata: {
      developer: "Capcom",
      publisher: "Capcom",
      releaseDate: "2023-03-24",
      genres: ["action", "horror", "adventure"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese", "Korean"],
    },
    editions: [
      { id: "g11-std", gameId: "g11", name: "Resident Evil 4", edition: "standard", includes: ["Base Game"] },
      { id: "g11-dlx", gameId: "g11", name: "Resident Evil 4 Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Separate Ways DLC", "Extra DLC Pack"] },
      { id: "g11-gld", gameId: "g11", name: "Resident Evil 4 Gold Edition", edition: "gold", includes: ["Base Game", "Separate Ways DLC", "Extra DLC Pack", "Mercenaries Mode"] },
    ],
    bestPrice: 27.99,
    bestPriceStoreId: "s6",
    originalPrice: 59.99,
    discount: 53,
    dealScore: 89,
    isOnSale: true,
  },
  {
    id: "g12",
    slug: "diablo-iv",
    title: "Diablo IV",
    coverImage: cover("Diablo IV"),
    description:
      "Lilith has returned to Sanctuary. Explore a dark, open world, customize your character from five classes, and battle the forces of Hell in this action RPG from Blizzard.",
    shortDescription: "Dark open-world action RPG from Blizzard Entertainment.",
    metadata: {
      developer: "Blizzard Entertainment",
      publisher: "Blizzard Entertainment",
      releaseDate: "2023-06-06",
      genres: ["action", "rpg", "open-world"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Co-op", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g12-std", gameId: "g12", name: "Diablo IV", edition: "standard", includes: ["Base Game"] },
      { id: "g12-dlx", gameId: "g12", name: "Diablo IV Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Battle Pass", "Cosmetic Set"] },
      { id: "g12-ult", gameId: "g12", name: "Diablo IV Ultimate Edition", edition: "ultimate", includes: ["Base Game", "Battle Pass", "Cosmetic Set", "Emote", "Wings of the Creator"] },
    ],
    bestPrice: 34.99,
    bestPriceStoreId: "s3",
    originalPrice: 69.99,
    discount: 50,
    dealScore: 80,
    isOnSale: true,
  },
  {
    id: "g13",
    slug: "lies-of-p",
    title: "Lies of P",
    coverImage: cover("Lies of P"),
    description:
      "A souls-like action RPG inspired by the tale of Pinocchio. Explore the ruined city of Krat, customize your combat style, and face ruthless enemies in this dark Belle Epoque world.",
    shortDescription: "Souls-like action RPG with a dark Pinocchio twist.",
    metadata: {
      developer: "Neowiz Games",
      publisher: "Neowiz Games",
      releaseDate: "2023-09-19",
      genres: ["action", "rpg", "souls-like"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g13-std", gameId: "g13", name: "Lies of P", edition: "standard", includes: ["Base Game"] },
      { id: "g13-dlx", gameId: "g13", name: "Lies of P Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Future DLC", "Cosmetic Pack"] },
    ],
    bestPrice: 29.99,
    bestPriceStoreId: "s5",
    originalPrice: 59.99,
    discount: 50,
    dealScore: 83,
    isOnSale: true,
  },
  {
    id: "g14",
    slug: "alan-wake-2",
    title: "Alan Wake 2",
    coverImage: cover("Alan Wake 2"),
    description:
      "Saga Anderson and Alan Wake navigate interconnected stories in this survival horror masterpiece. A genre-defying experience blending psychological horror with narrative innovation.",
    shortDescription: "Survival horror sequel blending dual narrative stories.",
    metadata: {
      developer: "Remedy Entertainment",
      publisher: "Epic Games Publishing",
      releaseDate: "2023-10-27",
      genres: ["horror", "action", "adventure"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean"],
    },
    editions: [
      { id: "g14-std", gameId: "g14", name: "Alan Wake 2", edition: "standard", includes: ["Base Game"] },
      { id: "g14-dlx", gameId: "g14", name: "Alan Wake 2 Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Expansion Pass", "Nordic Shotgun Skin"] },
    ],
    bestPrice: 39.99,
    bestPriceStoreId: "s3",
    originalPrice: 59.99,
    discount: 33,
    dealScore: 74,
    isOnSale: true,
  },
  {
    id: "g15",
    slug: "armored-core-vi-fires-of-rubicon",
    title: "Armored Core VI: Fires of Rubicon",
    coverImage: cover("Armored Core VI"),
    description:
      "FromSoftware's return to the mech action genre. Customize your mech with hundreds of parts and engage in intense 3D combat across a war-torn planet in this mission-based action game.",
    shortDescription: "FromSoftware's return to intense mech combat action.",
    metadata: {
      developer: "FromSoftware",
      publisher: "Bandai Namco Entertainment",
      releaseDate: "2023-08-25",
      genres: ["action"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g15-std", gameId: "g15", name: "Armored Core VI: Fires of Rubicon", edition: "standard", includes: ["Base Game"] },
      { id: "g15-dlx", gameId: "g15", name: "Armored Core VI Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Digital Artbook", "Digital Soundtrack"] },
    ],
    bestPrice: 34.99,
    bestPriceStoreId: "s6",
    originalPrice: 59.99,
    discount: 42,
    dealScore: 79,
    isOnSale: true,
  },
  {
    id: "g16",
    slug: "remnant-2",
    title: "Remnant 2",
    coverImage: cover("Remnant 2"),
    description:
      "The sequel to the best-selling Remnant: From the Ashes. Explore procedurally generated worlds alone or with friends, facing deadly creatures and epic bosses across multiple realms.",
    shortDescription: "Co-op souls-like shooter across procedural worlds.",
    metadata: {
      developer: "Gunfire Games",
      publisher: "Gearbox Publishing",
      releaseDate: "2023-07-25",
      genres: ["action", "rpg", "souls-like"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Multiplayer", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g16-std", gameId: "g16", name: "Remnant 2", edition: "standard", includes: ["Base Game"] },
      { id: "g16-ult", gameId: "g16", name: "Remnant 2 Ultimate Edition", edition: "ultimate", includes: ["Base Game", "All DLC", "Survival Pack"] },
    ],
    bestPrice: 24.99,
    bestPriceStoreId: "s4",
    originalPrice: 49.99,
    discount: 50,
    dealScore: 84,
    isOnSale: true,
  },
  {
    id: "g17",
    slug: "dead-space-remake",
    title: "Dead Space Remake",
    coverImage: cover("Dead Space"),
    description:
      "A rebuilt-from-the-ground-up remake of the sci-fi horror classic. Engineer Isaac Clarke must survive aboard the USG Ishimura, a vast mining ship infested with terrifying necromorphs.",
    shortDescription: "Stunning remake of the iconic sci-fi survival horror.",
    metadata: {
      developer: "Motive Studio",
      publisher: "Electronic Arts",
      releaseDate: "2023-01-27",
      genres: ["horror", "action"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese"],
    },
    editions: [
      { id: "g17-std", gameId: "g17", name: "Dead Space", edition: "standard", includes: ["Base Game"] },
      { id: "g17-dlx", gameId: "g17", name: "Dead Space Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Unique Suit", "Texture Pack"] },
    ],
    bestPrice: 23.99,
    bestPriceStoreId: "s5",
    originalPrice: 59.99,
    discount: 60,
    dealScore: 90,
    isOnSale: true,
  },
  {
    id: "g18",
    slug: "star-wars-jedi-survivor",
    title: "Star Wars Jedi: Survivor",
    coverImage: cover("Jedi Survivor"),
    description:
      "Continue Cal Kestis's journey in this action-adventure sequel. Master new Force abilities, discover new fighting styles, and explore a galaxy far, far away in stunning detail.",
    shortDescription: "Cal Kestis returns in this epic Star Wars action-adventure.",
    metadata: {
      developer: "Respawn Entertainment",
      publisher: "Electronic Arts",
      releaseDate: "2023-04-28",
      genres: ["action", "adventure"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese"],
    },
    editions: [
      { id: "g18-std", gameId: "g18", name: "Star Wars Jedi: Survivor", edition: "standard", includes: ["Base Game"] },
      { id: "g18-dlx", gameId: "g18", name: "Star Wars Jedi: Survivor Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Cosmetic Pack", "New Journey+ Perks"] },
    ],
    bestPrice: 27.99,
    bestPriceStoreId: "s3",
    originalPrice: 69.99,
    discount: 60,
    dealScore: 87,
    isOnSale: true,
  },
  {
    id: "g19",
    slug: "final-fantasy-xvi",
    title: "Final Fantasy XVI",
    coverImage: cover("Final Fantasy XVI"),
    description:
      "An all-new epic action RPG from Square Enix. Clive Rosfield embarks on a dark, mature journey through the land of Valisthea in this thrilling entry in the legendary franchise.",
    shortDescription: "Dark and mature action RPG in the Final Fantasy series.",
    metadata: {
      developer: "Square Enix",
      publisher: "Square Enix",
      releaseDate: "2024-09-17",
      genres: ["action", "rpg"],
      platforms: ["pc", "playstation"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean"],
    },
    editions: [
      { id: "g19-std", gameId: "g19", name: "Final Fantasy XVI", edition: "standard", includes: ["Base Game"] },
      { id: "g19-dlx", gameId: "g19", name: "Final Fantasy XVI Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Echoes of the Fallen DLC", "The Rising Tide DLC"] },
    ],
    bestPrice: 39.99,
    bestPriceStoreId: "s1",
    originalPrice: 49.99,
    discount: 20,
    dealScore: 72,
    isOnSale: true,
  },
  {
    id: "g20",
    slug: "palworld",
    title: "Palworld",
    coverImage: cover("Palworld"),
    description:
      "A multiplayer open-world survival crafting game where you befriend and collect mysterious creatures called Pals. Fight, farm, build, and work alongside your Pals in a vast open world.",
    shortDescription: "Open-world survival crafting with collectible creature companions.",
    metadata: {
      developer: "Pocketpair",
      publisher: "Pocketpair",
      releaseDate: "2024-01-19",
      genres: ["survival", "open-world", "adventure"],
      platforms: ["pc", "xbox"],
      features: ["Single Player", "Multiplayer", "Co-op", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g20-std", gameId: "g20", name: "Palworld", edition: "standard", includes: ["Base Game (Early Access)"] },
    ],
    bestPrice: 26.99,
    bestPriceStoreId: "s1",
    originalPrice: 29.99,
    discount: 10,
    dealScore: 65,
    isOnSale: true,
  },
  {
    id: "g21",
    slug: "helldivers-2",
    title: "Helldivers 2",
    coverImage: cover("Helldivers 2"),
    description:
      "Enlist in the Helldivers and fight for freedom in this intense co-op third-person shooter. Spread democracy across the galaxy with up to four friends against alien threats.",
    shortDescription: "Intense co-op third-person shooter for galactic democracy.",
    metadata: {
      developer: "Arrowhead Game Studios",
      publisher: "PlayStation PC LLC",
      releaseDate: "2024-02-08",
      genres: ["action", "fps"],
      platforms: ["pc", "playstation"],
      features: ["Multiplayer", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g21-std", gameId: "g21", name: "Helldivers 2", edition: "standard", includes: ["Base Game"] },
      { id: "g21-dlx", gameId: "g21", name: "Helldivers 2 Super Citizen Edition", edition: "deluxe", includes: ["Base Game", "Super Citizen Status", "Steeled Veterans Pack", "DP-53 Savior of the Free Stratagem"] },
    ],
    bestPrice: 31.99,
    bestPriceStoreId: "s1",
    originalPrice: 39.99,
    discount: 20,
    dealScore: 76,
    isOnSale: true,
  },
  {
    id: "g22",
    slug: "dragons-dogma-2",
    title: "Dragon's Dogma 2",
    coverImage: cover("Dragon's Dogma 2"),
    description:
      "An action RPG sequel featuring a vast open world, deep character creation, and the innovative Pawn system. Command AI companions as you explore a rich fantasy world full of adventure.",
    shortDescription: "Open-world action RPG with innovative AI companion system.",
    metadata: {
      developer: "Capcom",
      publisher: "Capcom",
      releaseDate: "2024-03-22",
      genres: ["action", "rpg", "open-world"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese", "Korean"],
    },
    editions: [
      { id: "g22-std", gameId: "g22", name: "Dragon's Dogma 2", edition: "standard", includes: ["Base Game"] },
      { id: "g22-dlx", gameId: "g22", name: "Dragon's Dogma 2 Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Camping Kit", "Wakestone Set", "Rift Crystals"] },
    ],
    bestPrice: 41.99,
    bestPriceStoreId: "s5",
    originalPrice: 69.99,
    discount: 40,
    dealScore: 75,
    isOnSale: true,
  },
  {
    id: "g23",
    slug: "black-myth-wukong",
    title: "Black Myth: Wukong",
    coverImage: cover("Black Myth Wukong"),
    description:
      "An action RPG rooted in Chinese mythology. As the Destined One, you shall venture into the perilous path and confront mighty foes in this visually stunning Journey to the West adaptation.",
    shortDescription: "Stunning action RPG based on the Chinese Journey to the West.",
    metadata: {
      developer: "Game Science",
      publisher: "Game Science",
      releaseDate: "2024-08-20",
      genres: ["action", "rpg", "souls-like"],
      platforms: ["pc", "playstation"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Chinese", "Japanese", "Korean"],
    },
    editions: [
      { id: "g23-std", gameId: "g23", name: "Black Myth: Wukong", edition: "standard", includes: ["Base Game"] },
      { id: "g23-dlx", gameId: "g23", name: "Black Myth: Wukong Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Digital Artbook", "Digital Soundtrack", "Equipment Set"] },
    ],
    bestPrice: 47.99,
    bestPriceStoreId: "s1",
    originalPrice: 59.99,
    discount: 20,
    dealScore: 71,
    isOnSale: true,
  },
  {
    id: "g24",
    slug: "stellar-blade",
    title: "Stellar Blade",
    coverImage: cover("Stellar Blade"),
    description:
      "A spectacular action-adventure game where humanity fights to reclaim Earth from invaders. Play as Eve, a skilled warrior sent from a space colony, in this visually stunning experience.",
    shortDescription: "Spectacular action-adventure to reclaim a ruined Earth.",
    metadata: {
      developer: "Shift Up",
      publisher: "Sony Interactive Entertainment",
      releaseDate: "2024-04-26",
      genres: ["action", "adventure"],
      platforms: ["playstation", "pc"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g24-std", gameId: "g24", name: "Stellar Blade", edition: "standard", includes: ["Base Game"] },
      { id: "g24-dlx", gameId: "g24", name: "Stellar Blade Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Cosmetic Pack", "Digital Artbook"] },
    ],
    bestPrice: 49.99,
    bestPriceStoreId: "s1",
    originalPrice: 59.99,
    discount: 17,
    dealScore: 64,
    isOnSale: true,
  },
  {
    id: "g25",
    slug: "indiana-jones-and-the-great-circle",
    title: "Indiana Jones and the Great Circle",
    coverImage: cover("Indiana Jones"),
    description:
      "Step into the boots of the legendary archaeologist in this first-person action-adventure set between Raiders of the Lost Ark and The Last Crusade. Uncover an ancient mystery spanning the globe.",
    shortDescription: "First-person adventure as the legendary archaeologist.",
    metadata: {
      developer: "MachineGames",
      publisher: "Bethesda Softworks",
      releaseDate: "2024-12-09",
      genres: ["action", "adventure"],
      platforms: ["pc", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese"],
    },
    editions: [
      { id: "g25-std", gameId: "g25", name: "Indiana Jones and the Great Circle", edition: "standard", includes: ["Base Game"] },
      { id: "g25-dlx", gameId: "g25", name: "Indiana Jones and the Great Circle Premium Edition", edition: "deluxe", includes: ["Base Game", "The Order of Giants DLC", "Digital Cosmetics Pack"] },
    ],
    bestPrice: 55.99,
    bestPriceStoreId: "s3",
    originalPrice: 69.99,
    discount: 20,
    dealScore: 66,
    isOnSale: true,
  },

  // ─── INDIE TITLES ────────────────────────────────────────────
  {
    id: "g26",
    slug: "hades",
    title: "Hades",
    coverImage: cover("Hades"),
    description:
      "Defy the god of the dead as you battle out of the Underworld in this rogue-like dungeon crawler. Wield the powers of Olympus, unravel the story, and grow stronger with each escape attempt.",
    shortDescription: "Rogue-like dungeon crawler from Supergiant Games.",
    metadata: {
      developer: "Supergiant Games",
      publisher: "Supergiant Games",
      releaseDate: "2020-09-17",
      genres: ["action", "roguelike", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese", "Russian"],
    },
    editions: [
      { id: "g26-std", gameId: "g26", name: "Hades", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s1",
    originalPrice: 24.99,
    discount: 60,
    dealScore: 94,
    isOnSale: true,
  },
  {
    id: "g27",
    slug: "celeste",
    title: "Celeste",
    coverImage: cover("Celeste"),
    description:
      "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain. A tight, rewarding platformer with a touching story about overcoming personal challenges.",
    shortDescription: "Precision platformer about climbing a mountain and yourself.",
    metadata: {
      developer: "Maddy Makes Games",
      publisher: "Maddy Makes Games",
      releaseDate: "2018-01-25",
      genres: ["platformer", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g27-std", gameId: "g27", name: "Celeste", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 4.99,
    bestPriceStoreId: "s1",
    originalPrice: 19.99,
    discount: 75,
    dealScore: 96,
    isOnSale: true,
  },
  {
    id: "g28",
    slug: "hollow-knight",
    title: "Hollow Knight",
    coverImage: cover("Hollow Knight"),
    description:
      "Descend into the vast, interconnected world of Hallownest. A beautifully hand-drawn 2D action-adventure with tight combat, challenging bosses, and deep exploration.",
    shortDescription: "Hand-drawn 2D action-adventure in a vast underground kingdom.",
    metadata: {
      developer: "Team Cherry",
      publisher: "Team Cherry",
      releaseDate: "2017-02-24",
      genres: ["action", "adventure", "platformer", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese", "Russian"],
    },
    editions: [
      { id: "g28-std", gameId: "g28", name: "Hollow Knight", edition: "standard", includes: ["Base Game", "All Free DLC (Grimm Troupe, Lifeblood, Godmaster)"] },
    ],
    bestPrice: 7.49,
    bestPriceStoreId: "s1",
    originalPrice: 14.99,
    discount: 50,
    dealScore: 95,
    isOnSale: true,
  },
  {
    id: "g29",
    slug: "stardew-valley",
    title: "Stardew Valley",
    coverImage: cover("Stardew Valley"),
    description:
      "Inherit your grandfather's old farm in Stardew Valley. Grow crops, raise animals, mine for resources, and become part of a vibrant community in this beloved farming RPG.",
    shortDescription: "Beloved farming RPG with crafting, relationships, and exploration.",
    metadata: {
      developer: "ConcernedApe",
      publisher: "ConcernedApe",
      releaseDate: "2016-02-26",
      genres: ["simulation", "rpg", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Multiplayer", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese", "Russian", "Turkish", "Hungarian"],
    },
    editions: [
      { id: "g29-std", gameId: "g29", name: "Stardew Valley", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 10.49,
    bestPriceStoreId: "s4",
    originalPrice: 14.99,
    discount: 30,
    dealScore: 88,
    isOnSale: true,
  },
  {
    id: "g30",
    slug: "terraria",
    title: "Terraria",
    coverImage: cover("Terraria"),
    description:
      "Dig, fight, explore, and build in this 2D sandbox adventure. With procedurally generated worlds and hundreds of items, there's always something new to discover in Terraria.",
    shortDescription: "2D sandbox adventure with endless crafting and exploration.",
    metadata: {
      developer: "Re-Logic",
      publisher: "Re-Logic",
      releaseDate: "2011-05-16",
      genres: ["adventure", "survival", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Multiplayer", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Chinese", "Russian"],
    },
    editions: [
      { id: "g30-std", gameId: "g30", name: "Terraria", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 4.99,
    bestPriceStoreId: "s1",
    originalPrice: 9.99,
    discount: 50,
    dealScore: 93,
    isOnSale: true,
  },
  {
    id: "g31",
    slug: "factorio",
    title: "Factorio",
    coverImage: cover("Factorio"),
    description:
      "Build and maintain massive automated factories. Mine resources, research technologies, build infrastructure, automate production, and fight alien creatures on a hostile planet.",
    shortDescription: "Addictive factory-building automation game.",
    metadata: {
      developer: "Wube Software",
      publisher: "Wube Software",
      releaseDate: "2020-08-14",
      genres: ["strategy", "simulation", "indie"],
      platforms: ["pc"],
      features: ["Single Player", "Multiplayer", "Co-op"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese", "Russian", "Polish"],
    },
    editions: [
      { id: "g31-std", gameId: "g31", name: "Factorio", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 35.00,
    bestPriceStoreId: "s1",
    originalPrice: 35.00,
    discount: 0,
    dealScore: 45,
    isOnSale: false,
  },
  {
    id: "g32",
    slug: "disco-elysium-the-final-cut",
    title: "Disco Elysium - The Final Cut",
    coverImage: cover("Disco Elysium"),
    description:
      "A groundbreaking open-world RPG where you are a detective with a unique skill system. Interrogate suspects, solve a murder mystery, and explore the city of Revachol in this dialogue-driven masterpiece.",
    shortDescription: "Groundbreaking detective RPG driven by dialogue and choices.",
    metadata: {
      developer: "ZA/UM",
      publisher: "ZA/UM",
      releaseDate: "2021-03-30",
      genres: ["rpg", "adventure", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player"],
      languages: ["English", "French", "German", "Spanish", "Portuguese", "Chinese", "Korean", "Polish"],
    },
    editions: [
      { id: "g32-std", gameId: "g32", name: "Disco Elysium - The Final Cut", edition: "standard", includes: ["Base Game", "The Final Cut Content"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s2",
    originalPrice: 39.99,
    discount: 75,
    dealScore: 96,
    isOnSale: true,
  },
  {
    id: "g33",
    slug: "outer-wilds",
    title: "Outer Wilds",
    coverImage: cover("Outer Wilds"),
    description:
      "Explore a solar system trapped in a time loop in this open-world mystery. Uncover the secrets of a lost alien civilization across handcrafted planets that evolve in real-time.",
    shortDescription: "Time-loop space exploration mystery across a solar system.",
    metadata: {
      developer: "Mobius Digital",
      publisher: "Annapurna Interactive",
      releaseDate: "2020-06-18",
      genres: ["adventure", "puzzle", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese"],
    },
    editions: [
      { id: "g33-std", gameId: "g33", name: "Outer Wilds", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s1",
    originalPrice: 24.99,
    discount: 60,
    dealScore: 93,
    isOnSale: true,
  },
  {
    id: "g34",
    slug: "cuphead",
    title: "Cuphead",
    coverImage: cover("Cuphead"),
    description:
      "A classic run-and-gun action game with stunning 1930s cartoon visuals. Fight spectacular bosses, learn their patterns, and traverse strange worlds in this challenging and charming experience.",
    shortDescription: "1930s cartoon-styled run-and-gun boss-rush action game.",
    metadata: {
      developer: "Studio MDHR",
      publisher: "Studio MDHR",
      releaseDate: "2017-09-29",
      genres: ["action", "platformer", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese", "Russian"],
    },
    editions: [
      { id: "g34-std", gameId: "g34", name: "Cuphead", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s4",
    originalPrice: 19.99,
    discount: 50,
    dealScore: 90,
    isOnSale: true,
  },
  {
    id: "g35",
    slug: "ori-and-the-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    coverImage: cover("Ori Will of Wisps"),
    description:
      "Embark on a new journey in a beautiful, hand-painted world. A visually stunning platformer with tight combat and a deeply emotional story about love, sacrifice, and hope.",
    shortDescription: "Visually stunning platformer with emotional storytelling.",
    metadata: {
      developer: "Moon Studios",
      publisher: "Xbox Game Studios",
      releaseDate: "2020-03-11",
      genres: ["platformer", "adventure", "indie"],
      platforms: ["pc", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese", "Russian"],
    },
    editions: [
      { id: "g35-std", gameId: "g35", name: "Ori and the Will of the Wisps", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 7.49,
    bestPriceStoreId: "s1",
    originalPrice: 29.99,
    discount: 75,
    dealScore: 95,
    isOnSale: true,
  },
  {
    id: "g36",
    slug: "slay-the-spire",
    title: "Slay the Spire",
    coverImage: cover("Slay the Spire"),
    description:
      "Craft a unique deck, encounter bizarre creatures, and discover relics of immense power. A genre-defining roguelike deck-builder that rewards strategic thinking and creativity.",
    shortDescription: "Genre-defining roguelike deck-building card game.",
    metadata: {
      developer: "Mega Crit Games",
      publisher: "Mega Crit Games",
      releaseDate: "2019-01-23",
      genres: ["strategy", "roguelike", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese", "Russian"],
    },
    editions: [
      { id: "g36-std", gameId: "g36", name: "Slay the Spire", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 8.49,
    bestPriceStoreId: "s4",
    originalPrice: 24.99,
    discount: 66,
    dealScore: 92,
    isOnSale: true,
  },
  {
    id: "g37",
    slug: "dead-cells",
    title: "Dead Cells",
    coverImage: cover("Dead Cells"),
    description:
      "A roguevania combining the best aspects of roguelike and metroidvania genres. Fast-paced combat, permadeath, and interconnected levels create endlessly replayable action.",
    shortDescription: "Fast-paced roguevania with brutal permadeath combat.",
    metadata: {
      developer: "Motion Twin",
      publisher: "Motion Twin",
      releaseDate: "2018-08-07",
      genres: ["action", "roguelike", "platformer", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese", "Russian"],
    },
    editions: [
      { id: "g37-std", gameId: "g37", name: "Dead Cells", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 7.49,
    bestPriceStoreId: "s1",
    originalPrice: 24.99,
    discount: 70,
    dealScore: 93,
    isOnSale: true,
  },
  {
    id: "g38",
    slug: "undertale",
    title: "Undertale",
    coverImage: cover("Undertale"),
    description:
      "A unique RPG where you don't have to kill anyone. Every enemy can be defeated through combat or through acts of mercy. Your choices genuinely matter in this unforgettable journey.",
    shortDescription: "Unique RPG where every enemy can be befriended.",
    metadata: {
      developer: "tobyfox",
      publisher: "tobyfox",
      releaseDate: "2015-09-15",
      genres: ["rpg", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player"],
      languages: ["English", "Japanese", "Chinese", "Korean"],
    },
    editions: [
      { id: "g38-std", gameId: "g38", name: "Undertale", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 4.99,
    bestPriceStoreId: "s1",
    originalPrice: 9.99,
    discount: 50,
    dealScore: 91,
    isOnSale: true,
  },
  {
    id: "g39",
    slug: "subnautica",
    title: "Subnautica",
    coverImage: cover("Subnautica"),
    description:
      "Descend into the depths of an alien underwater world. Craft equipment, pilot submarines, and explore a vast ocean full of wonders and dangers after crash-landing on an unknown planet.",
    shortDescription: "Underwater survival adventure on an alien ocean world.",
    metadata: {
      developer: "Unknown Worlds Entertainment",
      publisher: "Unknown Worlds Entertainment",
      releaseDate: "2018-01-23",
      genres: ["survival", "adventure", "open-world", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Russian", "Chinese", "Japanese"],
    },
    editions: [
      { id: "g39-std", gameId: "g39", name: "Subnautica", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s1",
    originalPrice: 29.99,
    discount: 67,
    dealScore: 93,
    isOnSale: true,
  },
  {
    id: "g40",
    slug: "valheim",
    title: "Valheim",
    coverImage: cover("Valheim"),
    description:
      "A Viking survival game where you explore a vast procedurally generated world, build mead halls, craft powerful weapons, and defeat mythical Norse bosses with up to 10 players.",
    shortDescription: "Viking survival and exploration with co-op multiplayer.",
    metadata: {
      developer: "Iron Gate AB",
      publisher: "Coffee Stain Publishing",
      releaseDate: "2021-02-02",
      genres: ["survival", "adventure", "open-world", "indie"],
      platforms: ["pc", "xbox"],
      features: ["Single Player", "Multiplayer", "Co-op", "Open World", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Japanese", "Chinese", "Korean", "Russian", "Swedish"],
    },
    editions: [
      { id: "g40-std", gameId: "g40", name: "Valheim", edition: "standard", includes: ["Base Game (Early Access)"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s1",
    originalPrice: 19.99,
    discount: 50,
    dealScore: 89,
    isOnSale: true,
  },
  {
    id: "g41",
    slug: "dave-the-diver",
    title: "Dave the Diver",
    coverImage: cover("Dave the Diver"),
    description:
      "Dive into the mysterious Blue Hole by day, catching fish and exploring underwater ruins. By night, run a sushi restaurant with your catches. A charming adventure blending genres seamlessly.",
    shortDescription: "Dive by day, run a sushi restaurant by night.",
    metadata: {
      developer: "Mintrocket",
      publisher: "Mintrocket",
      releaseDate: "2023-06-28",
      genres: ["adventure", "simulation", "indie"],
      platforms: ["pc", "playstation", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g41-std", gameId: "g41", name: "Dave the Diver", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 13.99,
    bestPriceStoreId: "s1",
    originalPrice: 19.99,
    discount: 30,
    dealScore: 85,
    isOnSale: true,
  },
  {
    id: "g42",
    slug: "lethal-company",
    title: "Lethal Company",
    coverImage: cover("Lethal Company"),
    description:
      "A co-op horror game about scavenging at abandoned moons to meet profit quotas for the Company. Navigate hazardous environments and terrifying creatures with your crew in this viral hit.",
    shortDescription: "Co-op horror scavenging game on abandoned moons.",
    metadata: {
      developer: "Zeekerss",
      publisher: "Zeekerss",
      releaseDate: "2023-10-23",
      genres: ["horror", "indie"],
      platforms: ["pc"],
      features: ["Multiplayer", "Co-op"],
      languages: ["English"],
    },
    editions: [
      { id: "g42-std", gameId: "g42", name: "Lethal Company", edition: "standard", includes: ["Base Game (Early Access)"] },
    ],
    bestPrice: 7.49,
    bestPriceStoreId: "s12",
    originalPrice: 9.99,
    discount: 25,
    dealScore: 82,
    isOnSale: true,
  },
  {
    id: "g43",
    slug: "balatro",
    title: "Balatro",
    coverImage: cover("Balatro"),
    description:
      "A hypnotic poker-themed roguelike deck-builder where you play illegal poker hands to beat blinds. Discover powerful jokers that break the rules and create insane synergies.",
    shortDescription: "Hypnotic poker roguelike deck-builder with wild jokers.",
    metadata: {
      developer: "LocalThunk",
      publisher: "Playstack",
      releaseDate: "2024-02-20",
      genres: ["strategy", "roguelike", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g43-std", gameId: "g43", name: "Balatro", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 11.24,
    bestPriceStoreId: "s1",
    originalPrice: 14.99,
    discount: 25,
    dealScore: 80,
    isOnSale: true,
  },
  {
    id: "g44",
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    coverImage: cover("Vampire Survivors"),
    description:
      "A time-survival game with minimalistic gameplay and roguelike elements. Mow down thousands of night creatures and survive until dawn in this absurdly addictive bullet-heaven experience.",
    shortDescription: "Addictive bullet-heaven survival with roguelike elements.",
    metadata: {
      developer: "poncle",
      publisher: "poncle",
      releaseDate: "2022-10-20",
      genres: ["action", "roguelike", "indie"],
      platforms: ["pc", "xbox", "nintendo"],
      features: ["Single Player", "Co-op", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g44-std", gameId: "g44", name: "Vampire Survivors", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 2.99,
    bestPriceStoreId: "s1",
    originalPrice: 4.99,
    discount: 40,
    dealScore: 91,
    isOnSale: true,
  },
  {
    id: "g45",
    slug: "inscryption",
    title: "Inscryption",
    coverImage: cover("Inscryption"),
    description:
      "A genre-bending card game odyssey that blends deckbuilding roguelike, escape room puzzles, and psychological horror into a darkly surreal and endlessly inventive experience.",
    shortDescription: "Genre-bending card game with escape room puzzles and horror.",
    metadata: {
      developer: "Daniel Mullins Games",
      publisher: "Devolver Digital",
      releaseDate: "2021-10-19",
      genres: ["strategy", "horror", "puzzle", "indie"],
      platforms: ["pc", "playstation", "nintendo"],
      features: ["Single Player"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g45-std", gameId: "g45", name: "Inscryption", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 6.99,
    bestPriceStoreId: "s4",
    originalPrice: 19.99,
    discount: 65,
    dealScore: 92,
    isOnSale: true,
  },
  {
    id: "g46",
    slug: "return-of-the-obra-dinn",
    title: "Return of the Obra Dinn",
    coverImage: cover("Obra Dinn"),
    description:
      "An insurance investigator boards a ghost ship to determine the fates of all 60 crew members. A unique 1-bit visual style and brilliant deductive puzzles make this a singular experience.",
    shortDescription: "Deductive puzzle game investigating a ghost ship's 60 missing crew.",
    metadata: {
      developer: "Lucas Pope",
      publisher: "3909",
      releaseDate: "2018-10-18",
      genres: ["puzzle", "adventure", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Chinese"],
    },
    editions: [
      { id: "g46-std", gameId: "g46", name: "Return of the Obra Dinn", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s1",
    originalPrice: 19.99,
    discount: 50,
    dealScore: 90,
    isOnSale: true,
  },
  {
    id: "g47",
    slug: "tunic",
    title: "Tunic",
    coverImage: cover("Tunic"),
    description:
      "An isometric action-adventure about a small fox on a big adventure. Explore a vast world, fight monsters, and discover secrets in this charming game inspired by classic action-adventure games.",
    shortDescription: "Isometric adventure about a small fox on a big quest.",
    metadata: {
      developer: "Andrew Shouldice",
      publisher: "Finji",
      releaseDate: "2022-03-16",
      genres: ["action", "adventure", "puzzle", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English"],
    },
    editions: [
      { id: "g47-std", gameId: "g47", name: "Tunic", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 11.99,
    bestPriceStoreId: "s3",
    originalPrice: 29.99,
    discount: 60,
    dealScore: 89,
    isOnSale: true,
  },
  {
    id: "g48",
    slug: "neon-white",
    title: "Neon White",
    coverImage: cover("Neon White"),
    description:
      "A lightning-fast first-person action game about slaying demons in Heaven. Use soul cards as weapons and movement abilities to shave precious seconds off your time in this speedrunner's paradise.",
    shortDescription: "Lightning-fast FPS card game about speedrunning through Heaven.",
    metadata: {
      developer: "Angel Matrix",
      publisher: "Annapurna Interactive",
      releaseDate: "2022-06-16",
      genres: ["action", "fps", "platformer", "indie"],
      platforms: ["pc", "playstation", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g48-std", gameId: "g48", name: "Neon White", edition: "standard", includes: ["Base Game"] },
    ],
    bestPrice: 9.99,
    bestPriceStoreId: "s1",
    originalPrice: 24.99,
    discount: 60,
    dealScore: 91,
    isOnSale: true,
  },
  {
    id: "g49",
    slug: "sifu",
    title: "Sifu",
    coverImage: cover("Sifu"),
    description:
      "A beat 'em up action game with a unique aging mechanic. Master kung fu, take revenge on those who murdered your family, and grow older and wiser with each death in this stylish brawler.",
    shortDescription: "Kung fu beat 'em up with a unique aging mechanic.",
    metadata: {
      developer: "Sloclap",
      publisher: "Sloclap",
      releaseDate: "2022-02-08",
      genres: ["action", "fighting", "indie"],
      platforms: ["pc", "playstation", "xbox", "nintendo"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g49-std", gameId: "g49", name: "Sifu", edition: "standard", includes: ["Base Game"] },
      { id: "g49-dlx", gameId: "g49", name: "Sifu Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Artbook", "Soundtrack", "Behind the Scenes"] },
    ],
    bestPrice: 13.99,
    bestPriceStoreId: "s3",
    originalPrice: 39.99,
    discount: 65,
    dealScore: 88,
    isOnSale: true,
  },
  {
    id: "g50",
    slug: "hi-fi-rush",
    title: "Hi-Fi Rush",
    coverImage: cover("Hi-Fi Rush"),
    description:
      "A rhythm-action game where the entire world moves to the beat. Play as wannabe rockstar Chai in this vibrant, cel-shaded adventure where combat, platforming, and music merge seamlessly.",
    shortDescription: "Vibrant rhythm-action adventure where the world moves to the beat.",
    metadata: {
      developer: "Tango Gameworks",
      publisher: "Bethesda Softworks",
      releaseDate: "2023-01-25",
      genres: ["action", "adventure", "indie"],
      platforms: ["pc", "playstation", "xbox"],
      features: ["Single Player", "Controller Support"],
      languages: ["English", "French", "German", "Spanish", "Italian", "Japanese", "Korean", "Chinese"],
    },
    editions: [
      { id: "g50-std", gameId: "g50", name: "Hi-Fi Rush", edition: "standard", includes: ["Base Game"] },
      { id: "g50-dlx", gameId: "g50", name: "Hi-Fi Rush Deluxe Edition", edition: "deluxe", includes: ["Base Game", "Bossplay Coop Pack", "Outfits"] },
    ],
    bestPrice: 14.99,
    bestPriceStoreId: "s1",
    originalPrice: 29.99,
    discount: 50,
    dealScore: 87,
    isOnSale: true,
  },
];
