import type { Store } from "@/lib/types";

export const mockStores: Store[] = [
  {
    id: "s1",
    name: "Steam",
    slug: "steam",
    logo: "https://placehold.co/80x80/1b2838/66c0f4?text=S",
    url: "https://store.steampowered.com",
    isOfficial: true,
    trustScore: 98,
    trustLevel: "excellent",
    totalReviews: 1_250_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA", "JP", "KR", "BR", "RU", "CN"],
    paymentMethods: ["Credit Card", "PayPal", "Steam Wallet", "Paysafecard", "Alipay", "WeChat Pay"],
    description:
      "The world's largest digital distribution platform for PC gaming. Operated by Valve Corporation, Steam offers an enormous catalog, community features, workshops, and regular seasonal sales.",
  },
  {
    id: "s2",
    name: "GOG",
    slug: "gog",
    logo: "https://placehold.co/80x80/5c2d91/d4a5ff?text=G",
    url: "https://www.gog.com",
    isOfficial: true,
    trustScore: 96,
    trustLevel: "excellent",
    totalReviews: 420_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA", "JP", "BR"],
    paymentMethods: ["Credit Card", "PayPal", "Paysafecard", "Bank Transfer"],
    description:
      "DRM-free digital distribution platform owned by CD Projekt. GOG specializes in classic and modern games with a strict no-DRM policy, ensuring players truly own their purchases.",
  },
  {
    id: "s3",
    name: "Epic Games Store",
    slug: "epic-games-store",
    logo: "https://placehold.co/80x80/0078f2/ffffff?text=E",
    url: "https://store.epicgames.com",
    isOfficial: true,
    trustScore: 94,
    trustLevel: "excellent",
    totalReviews: 680_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA", "JP", "KR", "BR"],
    paymentMethods: ["Credit Card", "PayPal", "Epic Wallet"],
    description:
      "Digital storefront by Epic Games, known for weekly free game giveaways and exclusive titles. Offers a curated selection with a lower revenue cut for developers.",
  },
  {
    id: "s4",
    name: "Humble Bundle",
    slug: "humble-bundle",
    logo: "https://placehold.co/80x80/cc2929/ffffff?text=H",
    url: "https://www.humblebundle.com",
    isOfficial: true,
    trustScore: 93,
    trustLevel: "excellent",
    totalReviews: 520_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA"],
    paymentMethods: ["Credit Card", "PayPal", "Amazon Pay", "Alipay"],
    description:
      "Digital storefront and subscription service known for charity bundles. Humble Choice offers monthly curated game bundles, and a portion of every purchase goes to charity.",
  },
  {
    id: "s5",
    name: "Green Man Gaming",
    slug: "green-man-gaming",
    logo: "https://placehold.co/80x80/00b853/ffffff?text=G",
    url: "https://www.greenmangaming.com",
    isOfficial: true,
    trustScore: 91,
    trustLevel: "excellent",
    totalReviews: 310_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA", "JP"],
    paymentMethods: ["Credit Card", "PayPal", "Paysafecard", "Bitcoin"],
    description:
      "Authorized digital retailer offering official game keys with competitive pricing. Known for frequent sales, VIP pricing tiers, and an XP reward system for loyal customers.",
  },
  {
    id: "s6",
    name: "Fanatical",
    slug: "fanatical",
    logo: "https://placehold.co/80x80/f47521/ffffff?text=F",
    url: "https://www.fanatical.com",
    isOfficial: true,
    trustScore: 89,
    trustLevel: "good",
    totalReviews: 245_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA"],
    paymentMethods: ["Credit Card", "PayPal", "Amazon Pay"],
    description:
      "Authorized key retailer formerly known as Bundle Stars. Fanatical is known for exclusive bundles, star deals, and a mystery key feature that offers random games at steep discounts.",
  },
  {
    id: "s7",
    name: "GamesPlanet",
    slug: "gamesplanet",
    logo: "https://placehold.co/80x80/e74c3c/ffffff?text=GP",
    url: "https://www.gamesplanet.com",
    isOfficial: true,
    trustScore: 88,
    trustLevel: "good",
    totalReviews: 185_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "DE", "FR"],
    paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
    description:
      "European-based authorized digital retailer with dedicated storefronts for UK, France, and Germany. Offers competitive pricing and regular flash deals on PC games.",
  },
  {
    id: "s8",
    name: "Voidu",
    slug: "voidu",
    logo: "https://placehold.co/80x80/00bcd4/ffffff?text=V",
    url: "https://www.voidu.com",
    isOfficial: true,
    trustScore: 85,
    trustLevel: "good",
    totalReviews: 78_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU"],
    paymentMethods: ["Credit Card", "PayPal", "iDEAL"],
    description:
      "Netherlands-based authorized game key retailer. Voidu partners directly with publishers to provide official keys at competitive prices with frequent discount codes.",
  },
  {
    id: "s9",
    name: "WinGameStore",
    slug: "wingamestore",
    logo: "https://placehold.co/80x80/2196f3/ffffff?text=W",
    url: "https://www.wingamestore.com",
    isOfficial: true,
    trustScore: 84,
    trustLevel: "good",
    totalReviews: 62_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "CA"],
    paymentMethods: ["Credit Card", "PayPal", "Amazon Pay"],
    description:
      "US-based authorized digital retailer offering Steam, Ubisoft Connect, and other platform keys. Known for consistent deals and straightforward purchasing experience.",
  },
  {
    id: "s10",
    name: "IndieGala",
    slug: "indiegala",
    logo: "https://placehold.co/80x80/e91e63/ffffff?text=I",
    url: "https://www.indiegala.com",
    isOfficial: true,
    trustScore: 82,
    trustLevel: "good",
    totalReviews: 135_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK", "AU", "CA"],
    paymentMethods: ["Credit Card", "PayPal", "Stripe"],
    description:
      "Digital storefront specializing in indie game bundles and deals. IndieGala offers a free game library, daily deals, and curated bundles featuring independent developers.",
  },
  {
    id: "s11",
    name: "GameBillet",
    slug: "gamebillet",
    logo: "https://placehold.co/80x80/4caf50/ffffff?text=GB",
    url: "https://www.gamebillet.com",
    isOfficial: true,
    trustScore: 80,
    trustLevel: "good",
    totalReviews: 42_000,
    avgDeliveryTime: "Instant",
    regionSupport: ["US", "EU", "UK"],
    paymentMethods: ["Credit Card", "PayPal"],
    description:
      "Authorized digital retailer offering competitive prices on PC game keys. GameBillet works directly with publishers and frequently offers some of the lowest official prices available.",
  },
  {
    id: "s12",
    name: "CDKeys",
    slug: "cdkeys",
    logo: "https://placehold.co/80x80/ff9800/ffffff?text=CD",
    url: "https://www.cdkeys.com",
    isOfficial: false,
    trustScore: 72,
    trustLevel: "average",
    totalReviews: 890_000,
    avgDeliveryTime: "1-15 minutes",
    regionSupport: ["US", "EU", "UK", "AU", "CA"],
    paymentMethods: ["Credit Card", "PayPal", "Apple Pay", "Google Pay"],
    description:
      "Grey market key reseller offering discounted game keys for PC, PlayStation, Xbox, and Nintendo. While not an authorized retailer, CDKeys has built a large customer base with competitive pricing.",
  },
  {
    id: "s13",
    name: "Eneba",
    slug: "eneba",
    logo: "https://placehold.co/80x80/00c853/ffffff?text=En",
    url: "https://www.eneba.com",
    isOfficial: false,
    trustScore: 68,
    trustLevel: "average",
    totalReviews: 650_000,
    avgDeliveryTime: "1-30 minutes",
    regionSupport: ["US", "EU", "UK", "AU", "CA", "BR"],
    paymentMethods: ["Credit Card", "PayPal", "Paysafecard", "Crypto"],
    description:
      "Grey market marketplace where third-party sellers list game keys. Eneba offers buyer protection and competitive prices but keys come from individual sellers rather than publishers.",
  },
  {
    id: "s14",
    name: "G2A",
    slug: "g2a",
    logo: "https://placehold.co/80x80/f44336/ffffff?text=G2",
    url: "https://www.g2a.com",
    isOfficial: false,
    trustScore: 55,
    trustLevel: "average",
    totalReviews: 1_100_000,
    avgDeliveryTime: "1-60 minutes",
    regionSupport: ["US", "EU", "UK", "AU", "CA", "BR", "RU"],
    paymentMethods: ["Credit Card", "PayPal", "Paysafecard", "Crypto", "Skrill"],
    description:
      "Large grey market marketplace for game keys and digital products. G2A connects buyers with individual sellers. Offers G2A Shield buyer protection but has faced controversy regarding key sourcing.",
  },
  {
    id: "s15",
    name: "Kinguin",
    slug: "kinguin",
    logo: "https://placehold.co/80x80/0066cc/ffffff?text=K",
    url: "https://www.kinguin.net",
    isOfficial: false,
    trustScore: 52,
    trustLevel: "average",
    totalReviews: 780_000,
    avgDeliveryTime: "1-60 minutes",
    regionSupport: ["US", "EU", "UK", "AU", "CA"],
    paymentMethods: ["Credit Card", "PayPal", "Paysafecard", "Crypto", "Skrill"],
    description:
      "Grey market digital marketplace offering game keys from third-party sellers. Kinguin provides buyer protection services but prices and seller reliability can vary significantly.",
  },
];
